### PR TITLE
Implement hotreloading for macOS and Windows and other bugfixes

### LINKED ISSUE #45: Build issue: Make readdir, closedir, opendir static in nob.h
```
raylib.lib(rcore.obj) : error LNK2005: opendir already defined in plug.obj
raylib.lib(rcore.obj) : error LNK2005: closedir already defined in plug.obj
raylib.lib(rcore.obj) : error LNK2005: readdir already defined in plug.obj
```
Both rcore.c and plug.c (via nob.h) export opendir, closedir and readdir. This results in a linker error. I fixed it currently by declaring them static in nob.h.

### LINKED ISSUE #73: I cannot build on Windows ...
... Probably because I am too stupid to work nob.exe, but here's what happens when I try:
 ----------------------------------------------------------------------------------------------------

Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd /d c:\users\DEVNVME\Desktop\musializer

c:\Users\DevNVME\Desktop\musializer>"C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/Build/vcvarsall.bat" x86_amd64
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.8.3
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86_x64'

c:\Users\DevNVME\Desktop\musializer>cl.exe nob.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nob.c
Microsoft (R) Incremental Linker Version 14.38.33133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nob.exe
nob.obj

c:\Users\DevNVME\Desktop\musializer>nob.exe
[INFO] --- STAGE 1 ---
[INFO] created directory `build`
[INFO] Generating ./build/config.h
[INFO] CMD: cl.exe nob.c -DCONFIGURED
Microsoft (R) C/C++ Optimizing Compiler Version 19.38.33133 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

nob.c
Microsoft (R) Incremental Linker Version 14.38.33133.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:nob.exe
nob.obj
LINK : fatal error LNK1104: cannot open file 'nob.exe'
[ERROR] command exited with exit code 2

### PR DESCRIPTION
**Pull request by Markos-Th09**
Implements hot reloading for macOS and windows

Closes #45
Closes #73

### CODE REVIEW

**Comment by rexim** [comment]
Thank you for the PR! Unfortunately I do not accept feature implementations as per [CONTRIBUTING.md](https://github.com/tsoding/musializer/blob/088ec58ba6b0f4a7f5904351d78e8ddc19c7254c/CONTRIBUTING.md) sorry.

**Comment by Markos-Th09** [comment]
I understand. Are you planning to implement hotreloading on other platforms yourself any time soon?

**Comment by Markos-Th09** [comment]
I will extract the bug fixes and typo corrections into a new PR without the hotreloading part

**Comment by Markos-Th09** [comment]
Why did you deny this PR but allowed #81 to be merged, which is clearly also a feature implementation? Is there something I am not understanding correctly from CONTRIBUTING.md?

**Pull request closed without merging**
