### PR TITLE
add hotreload support for windows

### PR DESCRIPTION
**Pull request by Markos-Th09**
Adds hotreload support for the niche video game operating system, for both msvc and mingw.

### CODE REVIEW

**Comment by rexim** [comment]
Is it suppose to work in wine as well? I haven't check the native Windows, but it crashes on wine with "Unhandled page fault on read access". It would be kinda cool if it worked in wine too. :(

**Comment by Markos-Th09** [comment]
> Is it suppose to work in wine as well? I haven't check the native Windows, but it crashes on wine with "Unhandled page fault on read access". It would be kinda cool if it worked in wine too. :(

This is actually my fault, thank for pointing it out. I didn't realize the new resource loading added new plug functions after the bundling. For future reference after this is merged, make sure to add `MUSIALIZER_PLUG` before those to maintain windows compatibility.

**Comment by rexim** [comment]
@Markos-Th09 alright, looks good! Thank you!

**Comment by Markos-Th09** [comment]
> @Markos-Th09 alright, looks good! Thank you!

On a completely unrelated note, why was #74 closed but this is accepted?

**Comment by Markos-Th09** [comment]
also I did a bit of a messup check out #98

**Pull request merged**
