### PR TITLE
Update miniaudio to fix audio on macOS

### LINKED ISSUE #35: Build succeed on macOS. No audio, Visualizing works perfectly. [Fixed]
- I am using a macOS Apple Silicon.
- The build works just fine. ```./nob config && ./nob build``` (Although i am getting some warning that in nob.c the switch case doesn't handle macOS, maybe that's the cause of the issue)
- The audio doesn't work. no music is playing. although the visualization is perfect.

### PR DESCRIPTION
**Pull request by auxves**
This change has already been merged in raylib master.

I've tested on macOS and Linux and it fixes the audio issue!

Feel free to diff against the upstream file to verify it hasn't been modified: https://github.com/raysan5/raylib/blob/b46505b13d4a85e26d1d5b6f9fc2a4264bf8b02f/src/external/miniaudio.h

Closes #35

### CODE REVIEW

**Comment by yhbsh** [comment]
i have downloaded you version of the program.
```console
$ git clone https://github.com/auxves/musializer.git
```
compiled it 
```console
$ cc -o nob nob.c
$ ./nob
```
and ran it
```console
./build/musializer
```

and still the same problem!.

I know that miniaudio fixed their macOS issue, i tested miniaudio separately and it works. but for some reason musializer doesn't event though we're using the latest miniaudio version (dev branch). maybe something to do with the plug dynamic library? i don't know. please tell me what you did so that the program worked for you.

**Comment by auxves** [comment]
Did you use the right branch (`update-miniaudio`)? On my system, simply updating the miniaudio header fixed the problem.

**Comment by yhbsh** [comment]
yes i did! i cloned the fork version right from your account. i know it is weird. i will do more research.

**Comment by nicolasdanelon** [comment]
hey @rexim I pull the master branch and I have sound now, but every thing seems a little bit big
Screenshot 2023-11-23 at 19 05 19

**Comment by nicolasdanelon** [comment]
like a charm :)
https://github.com/tsoding/musializer/assets/2846046/2ec1ef4f-5fe2-467d-ae1c-686a60219b34

**Comment by yhbsh** [comment]
yeah i experienced it also. i think this is related to raylib changing some of their internal apis, which caused this weird behavior, because the src folder of musializer did not change between the last and second-last commits.

**Comment by auxves** [comment]
As this specific issue is resolved with Raylib 5.0, I'll close this PR. Check out #56 for the scaling issue :)

**Pull request closed without merging**
