### PR TITLE
additional fixes for the windows support by yul4140

### PR DESCRIPTION
**Pull request by T-r-y-o-k-s**
This is based on [yul4140](https://github.com/yuI4140)'s support for Windows and just adds some small details.
Now it also fixes the link to @null.

### CODE REVIEW

**Comment by yuI4140** [comment]
looks good uwu

**Comment by yuI4140** [comment]
there is a problem with the removing files change that part of the build.bat for this:
```bat

set "processName=musializer.exe"
set "dirPath=.\build"  

tasklist /fi "imagename eq %processName%" | find /i "%processName%" > nul
if errorlevel 1 (
    echo The process %processName% is not running.
) else (
    echo Terminating the process %processName%...
    taskkill /F /IM %processName%
)

if exist "%dirPath%" (
    echo Removing the directory %dirPath%...
    rmdir /s /q "%dirPath%"
) else (
    echo The directory %dirPath% does not exist.
)
mkdir build
````
this  check if the folder and the process is running and if it revome after that  create the folder again

**Comment by yuI4140** [comment]
> > there is a problem with the removing files change that part of the build.bat for this:
> > ```batchfile
> > set "processName=musializer.exe"
> > set "dirPath=.\build"  
> > 
> > tasklist /fi "imagename eq %processName%" | find /i "%processName%" > nul
> > if errorlevel 1 (
> >     echo The process %processName% is not running.
> > ) else (
> >     echo Terminating the process %processName%...
> >     taskkill /F /IM %processName%
> > )
> > 
> > if exist "%dirPath%" (
> >     echo Removing the directory %dirPath%...
> >     rmdir /s /q "%dirPath%"
> > ) else (
> >     echo The directory %dirPath% does not exist.
> > )
> > mkdir build
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > this check if the folder and the process is running and if it, remove it after that create the folder again. btw When you have files into ./build it throw an error ( it denied to remve the files) and I didn't know how to fix it , I was thinking in change the permissions but it didn't work .
> 
> Thanks for the suggestions! I didn't encounter that error, `rmdir /s` should be able to remove everything under that folder.

fix the merge confflict btw

**Comment by T-r-y-o-k-s** [comment]
I don't know how to do that, feel free to incorporate my changes. I give up trying to understand git

**Pull request closed without merging**
