### PR TITLE
windows_support

### PR DESCRIPTION
**Pull request by yuI4140**
I created a new folder named 'win_support' to hold the binaries and headers required for building raylib. I faced issues with 'windows.h' due to duplicate values. I solved this by moving 'reload_libplug' to its own '.c' file and creating a separate 'plug.h' without the 'raylib' inclusion. This fix worked. Feel free to ask if you have more questions.

### CODE REVIEW

**Comment by rexim** [comment]
How am I suppose to review 13k added lines? :flushed:

**Comment by yuI4140** [comment]
xd

**Comment by yuI4140** [comment]
OOOH no! I forgot change the build.bat

**Comment by yuI4140** [comment]
> How am I suppose to review 13k added lines? 😳

btw not merge cuz I do not change the build.bat xd

**Comment by yuI4140** [comment]
> > How am I suppose to review 13k added lines? 😳
> 
> btw not merge cuz I do not change the build.bat xd

Done

**Pull request closed without merging**
