### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by yuI4140**
I created a new folder named 'win_support' to hold the binaries and headers required for building raylib. I faced issues with 'windows.h' due to duplicate values. I solved this by moving 'reload_libplug' to its own '.c' file and creating a separate 'plug.h' without the 'raylib' inclusion. This fix worked. Feel free to ask if you have more questions.

pd:sorry I closed it

### CODE REVIEW

**Comment by rexim** [comment]
How am I suppose to review 13k added lines? 😳

**Comment by yuI4140** [comment]
> How am I suppose to review 13k added lines? 😳

the only  thing I did is the reload_libplug. the rest is copy paste from the originals codes

**Comment by yuI4140** [comment]
> > How am I suppose to review 13k added lines? 😳
> 
> the only  thing I did is the reload_libplug. the rest is copy paste from the originals codes 

also I did the build.bat and nothing else  lmao

**Comment by yuI4140** [comment]
> How am I suppose to review 13k added lines? 😳

also you are beautiful as good programmers do. we send the diff to an AI and We force it  to tell us the difference xd

**Comment by yuI4140** [comment]
I swear I don't believe the .md again, oh god cuz  it has a conflict with the merge and worst of all is that the ploblem comes from  the  README.md.  
 :( well I think you can not do merge so at least they have my port of the musializer

**Comment by yuI4140** [comment]
> How am I suppose to review 13k added lines? 😳

Btw if you ask me why there are too many commits it's becouse I didn't know how to fix a merge conflict xd.

**Comment by yuI4140** [comment]
> How am I suppose to review 13k added lines? 😳

now Is only 6k. I will do a chengelog here: 
- add a #ifdef __linux__ for include the dlfcn.h 
- add a #ifdef _WIN32 for reload_libplug  and then link it with the modified version for windows
- add a modify version of plug.h ( fixing the ploblem with the overide between windows.h and raylib)
- add a build.bat ( change the gcc with clang if you like) 

 *That's all I've added the rest is the Raylib lib and the .h of it all of these is on the win_support folder except of the build.bat*

**Pull request closed without merging**
