### PR TITLE
Make timeline height adaptive

### PR DESCRIPTION
**Pull request by AMurkin**
1/6 of total height, but 24px min and 150px max

### CODE REVIEW

**Comment by rexim** [comment]
Why?

**Comment by AMurkin** [comment]
Because now it gets too big for small window size and disproportionately small for big window size.

**Comment by rexim** [comment]
That's the case for the majority of apps with side panels.

**Comment by AMurkin** [comment]
Unless its UI is adaptive maybe? Dunno. A matter of taste, perhaps.

**Comment by rexim** [comment]
Yeah, I also think it's a matter of taste. Thank you for the PR!

**Pull request closed without merging**
